scripts:
stylesheets:
author: Adeptus Ineptus

# Where things are
source: _site
destination: public_html
sass:
  style: compressed

# Outputting
timezone: America/New_York

# Outputting
defaults:
  -
    values:
      layout: army_list
  -
    scope:
      path: assets
    values:
      layout: none

# Theme
theme: baseline
