scripts:
stylesheets:
author: Adeptus Ineptus

# Where things are
source: _site
destination: public_html
sass:
  style: compressed
collections:
  army_lists:
    output: true
    permalink: army-lists/:name:output_ext
  faqs:
  forces:
  special_rules:
  units:
  weapons:

# Outputting
timezone: America/New_York

# Outputting
defaults:
  -
    values:
      layout: default
  -
    scope:
      path: assets
    values:
      layout: none
  -
    scope:
      type: army_lists
    values:
      layout: army_list

# Theme
theme: baseline
